name: Build and Run Example Project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Install Plugin
        run: mvn install

      - name: Upload Plugin Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ~/.m2/repository/com/ly/smart-doc
          if-no-files-found: error

  gen-rest-api-doc:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: generate-rest-api-doc
      cancel-in-progress: true

    steps:
    - name: Checkout Example Project
      uses: actions/checkout@v4
      with:
        repository: smart-doc-group/smart-doc-example-cn
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Install Example Project
      run: mvn -DskipTests=true install

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: smart-doc-maven-jar
        path: ./artifacts

    - name: Move Files to Local Maven Repository
      run: |
        mkdir -p ~/.m2/repository/com/ly/smart-doc
        echo "Overwriting target directory with new artifacts:"
        rsync -av --delete ./artifacts/ ~/.m2/repository/com/ly/smart-doc/
        echo "Listing files in target directory:"
        ls -lh ~/.m2/repository/com/ly/smart-doc


    - name: Generate AsciiDoc Documentation
      run: mvn -DskipTests=true smart-doc:adoc

    - name: Generate HTML Documentation
      run: mvn -DskipTests=true smart-doc:html

    - name: Generate JMeter Documentation
      run: mvn -DskipTests=true smart-doc:jmeter

    - name: Generate Markdown Documentation
      run: mvn -DskipTests=true smart-doc:markdown

    - name: Generate OpenAPI Documentation
      run: mvn -DskipTests=true smart-doc:openapi

    - name: Generate Postman Documentation
      run: mvn -DskipTests=true smart-doc:postman

    - name: Generate Word Documentation
      run: mvn -DskipTests=true smart-doc:word

  gen-dubbo-api-doc:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: generate-dubbo-api-doc
      cancel-in-progress: true

    steps:
      - name: Checkout Example Project
        uses: actions/checkout@v4
        with:
          repository: smart-doc-group/smart-doc-example-cn
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Install Example Project
        run: mvn -DskipTests=true install

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ./artifacts

      - name: Move Files to Local Maven Repository
        run: |
          mkdir -p ~/.m2/repository/com/ly/smart-doc
          echo "Overwriting target directory with new artifacts:"
          rsync -av --delete ./artifacts/ ~/.m2/repository/com/ly/smart-doc/
          echo "Listing files in target directory:"
          ls -lh ~/.m2/repository/com/ly/smart-doc


      - name: Generate RPC AsciiDoc Documentation
        run: mvn -DskipTests=true smart-doc:rpc-adoc

      - name: Generate RPC HTML Documentation
        run: mvn -DskipTests=true smart-doc:rpc-html

      - name: Generate RPC Markdown Documentation
        run: mvn -DskipTests=true smart-doc:rpc-markdown

  gen-javadoc-api-doc:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: generate-javadoc-api-doc
      cancel-in-progress: true

    steps:
      - name: Checkout Example Project
        uses: actions/checkout@v4
        with:
          repository: smart-doc-group/smart-doc-example-cn
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Install Example Project
        run: mvn -DskipTests=true install

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ./artifacts

      - name: Move Files to Local Maven Repository
        run: |
          mkdir -p ~/.m2/repository/com/ly/smart-doc
          echo "Overwriting target directory with new artifacts:"
          rsync -av --delete ./artifacts/ ~/.m2/repository/com/ly/smart-doc/
          echo "Listing files in target directory:"
          ls -lh ~/.m2/repository/com/ly/smart-doc


      - name: Generate Javadoc AsciiDoc Documentation
        run: mvn -DskipTests=true smart-doc:javadoc-adoc

      - name: Generate Javadoc HTML Documentation
        run: mvn -DskipTests=true smart-doc:javadoc-html

      - name: Generate Javadoc Markdown Documentation
        run: mvn -DskipTests=true smart-doc:javadoc-markdown

  gen-websocket-api-doc:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: generate-websocket-api-doc
      cancel-in-progress: true

    steps:
      - name: Checkout Example Project
        uses: actions/checkout@v4
        with:
          repository: smart-doc-group/smart-doc-example-cn
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Install Example Project
        run: mvn -DskipTests=true install

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ./artifacts

      - name: Move Files to Local Maven Repository
        run: |
          mkdir -p ~/.m2/repository/com/ly/smart-doc
          echo "Overwriting target directory with new artifacts:"
          rsync -av --delete ./artifacts/ ~/.m2/repository/com/ly/smart-doc/
          echo "Listing files in target directory:"
          ls -lh ~/.m2/repository/com/ly/smart-doc


      - name: Generate WebSocket Markdown Documentation
        run: mvn -DskipTests=true smart-doc:websocket-markdown